@echo off
setlocal
for %%F in (
  PHASE136_AUDIT_REPORT.md
  PHASE136_BROWSER_VALIDATION.json
  PHASE136_CHANGED_FILES.txt
  PHASE136_CLEANUP.bat
  PHASE136_CLEANUP_LIST.txt
  PHASE136_CONFIG_VALIDATION.json
  PHASE136_PAGE_STATUS.json
  PHASE136_PAGE_STATUS.md
  PHASE136_REMAINING_LIMITATIONS.md
  PHASE136_TEST_CHECKLIST.md
  PHASE136_VALIDATION.json
  README_PHASE136_REAL_ENVIRONMENT_VERIFICATION.md
) do (
  if exist "%%F" del /q "%%F"
)
echo Phase 137 documentation cleanup complete.
endlocal
