<?php
require_once __DIR__ . '/_header.php';
if (!table_exists('admin_audit_events')) {
    ?><div class="panel-card wf149-db-required"><h2>Admin Audit Log is waiting for the database upgrade.</h2><p>Import <code>sql/phase148_critical_backend_hardening.sql</code>, then reload this page. Until then this page stays safely disabled instead of crashing.</p><div class="admin-actions"><a class="btn btn-primary" href="system-check.php">Open System Check</a><a class="btn btn-soft" href="dashboard.php">Back to Dashboard</a></div></div><?php require_once __DIR__ . '/_footer.php'; exit;
}
$page=max(1,(int)($_GET['page']??1));$per=80;$off=($page-1)*$per;$q=trim((string)($_GET['q']??''));$where='';$params=[];if($q!==''){$where=' WHERE (e.event_type LIKE ? OR e.entity_type LIKE ? OR e.entity_id LIKE ? OR e.event_note LIKE ? OR a.name LIKE ?)';$params=array_fill(0,5,'%'.$q.'%');}
$c=db()->prepare('SELECT COUNT(*) FROM admin_audit_events e LEFT JOIN admins a ON a.id=e.admin_id'.$where);$c->execute($params);$count=(int)$c->fetchColumn();$stmt=db()->prepare('SELECT e.*,a.name admin_name FROM admin_audit_events e LEFT JOIN admins a ON a.id=e.admin_id'.$where.' ORDER BY e.id DESC LIMIT '.$per.' OFFSET '.$off);$stmt->execute($params);$rows=$stmt->fetchAll();$pages=max(1,(int)ceil($count/$per));
?>
<div class="admin-top"><div><h1>Administrator Audit Log</h1><p>Append-only security and administrative activity history.</p></div><form method="get"><input name="q" value="<?=e($q)?>" placeholder="Search action, admin or entity"><button class="btn btn-sm btn-dark">Search</button></form></div><div class="panel-card"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Admin</th><th>Action</th><th>Entity</th><th>Note</th><th>IP</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td data-label="Date"><?=e($r['created_at'])?></td><td data-label="Admin"><?=e($r['admin_name']??'System')?></td><td data-label="Action"><strong><?=e($r['event_type'])?></strong></td><td data-label="Entity"><?=e(trim(($r['entity_type']??'').' #'.($r['entity_id']??''),' #'))?></td><td data-label="Note"><?=e($r['event_note']??'')?></td><td data-label="IP"><?=e($r['ip_address']??'')?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="6" class="empty-state">No audit events found.</td></tr><?php endif;?></tbody></table></div><div class="pagination"><?php if($page>1):?><a class="btn btn-sm btn-soft" href="?page=<?=$page-1?>&q=<?=e(rawurlencode($q))?>">Previous</a><?php endif;?><span>Page <?=$page?> / <?=$pages?></span><?php if($page<$pages):?><a class="btn btn-sm btn-soft" href="?page=<?=$page+1?>&q=<?=e(rawurlencode($q))?>">Next</a><?php endif;?></div></div>
<?php require_once __DIR__ . '/_footer.php'; ?>
