<?php require_once __DIR__ . '/_header.php';
ensure_schema_updates();
$edit = null;
if (isset($_GET['edit'])) { $stmt = db()->prepare('SELECT * FROM batch_timings WHERE id=?'); $stmt->execute([(int)$_GET['edit']]); $edit = $stmt->fetch(); }
if ($_SERVER['REQUEST_METHOD'] === 'POST' && csrf_validate($_POST['csrf_token'] ?? '')) {
    $action = $_POST['action'] ?? '';
    if ($action === 'delete') { $stmt = db()->prepare('DELETE FROM batch_timings WHERE id=?'); $stmt->execute([(int)($_POST['id'] ?? 0)]); flash('success', 'Batch deleted.'); redirect('batches.php'); }
    $batch_name = trim($_POST['batch_name'] ?? ''); $course_name = trim($_POST['course_name'] ?? ''); $timing = trim($_POST['timing'] ?? ''); $days = trim($_POST['days'] ?? ''); $seats_note = trim($_POST['seats_note'] ?? ''); $sort_order = (int)($_POST['sort_order'] ?? 0); $published = ($_POST['published'] ?? 'Yes') === 'No' ? 'No' : 'Yes';
    if ($batch_name === '') { flash('error', 'Batch name is required.'); redirect('batches.php' . ($action === 'update' ? '?edit=' . (int)($_POST['id'] ?? 0) : '')); }
    if ($action === 'add') { $stmt = db()->prepare('INSERT INTO batch_timings (batch_name, course_name, timing, days, seats_note, sort_order, published) VALUES (?, ?, ?, ?, ?, ?, ?)'); $stmt->execute([$batch_name, $course_name, $timing, $days, $seats_note, $sort_order, $published]); flash('success', 'Batch added.'); redirect('batches.php'); }
    if ($action === 'update') { $stmt = db()->prepare('UPDATE batch_timings SET batch_name=?, course_name=?, timing=?, days=?, seats_note=?, sort_order=?, published=? WHERE id=?'); $stmt->execute([$batch_name, $course_name, $timing, $days, $seats_note, $sort_order, $published, (int)($_POST['id'] ?? 0)]); flash('success', 'Batch updated.'); redirect('batches.php'); }
}
$q = trim($_GET['q'] ?? ''); $where=''; $params=[]; if ($q !== '') { $where=' WHERE batch_name LIKE ? OR course_name LIKE ? OR timing LIKE ? OR days LIKE ?'; $params=["%$q%","%$q%","%$q%","%$q%"]; }
$stmt = db()->prepare('SELECT * FROM batch_timings' . $where . ' ORDER BY sort_order ASC, id DESC LIMIT 200'); $stmt->execute($params); $rows=$stmt->fetchAll();
$courses = db()->query('SELECT title FROM courses ORDER BY sort_order ASC, title ASC')->fetchAll();
?>
<div class="admin-top"><div><h1>Batch Timing Management</h1><p>Manage visible batch timings, course groups, available days and urgency notes.</p></div><a class="btn btn-soft" href="../admission.php" target="_blank">View Admission</a></div>
<?php if ($msg = flash('success')): ?><div class="alert alert-success"><?= e($msg) ?></div><?php endif; ?><?php if ($msg = flash('error')): ?><div class="alert alert-danger"><?= e($msg) ?></div><?php endif; ?>
<form class="form-box" method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="<?= $edit ? 'update' : 'add' ?>"><?php if ($edit): ?><input type="hidden" name="id" value="<?= e((string)$edit['id']) ?>"><?php endif; ?><div class="form-grid"><div class="form-section-title"><span>🕒</span><?= $edit ? 'Edit Batch' : 'Add Batch Timing' ?></div><div class="field"><label>Batch Name *</label><input name="batch_name" value="<?= e($edit['batch_name'] ?? '') ?>" placeholder="Morning Speaking Batch" required></div><div class="field"><label>Course Name</label><select name="course_name"><option value="">Select course</option><?php foreach ($courses as $course): ?><option value="<?= e($course['title']) ?>" <?= ($edit['course_name'] ?? '') === $course['title'] ? 'selected' : '' ?>><?= e($course['title']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Timing</label><input name="timing" value="<?= e($edit['timing'] ?? '') ?>" placeholder="7:00 AM - 8:00 AM"></div><div class="field"><label>Days</label><input name="days" value="<?= e($edit['days'] ?? '') ?>" placeholder="Mon to Sat"></div><div class="field full"><label>Seats / Urgency Note</label><input name="seats_note" value="<?= e($edit['seats_note'] ?? '') ?>" placeholder="Limited seats available this week"></div><div class="field"><label>Sort Order</label><input type="number" name="sort_order" value="<?= e((string)($edit['sort_order'] ?? 0)) ?>"></div><div class="field"><label>Published</label><select name="published"><option value="Yes" <?= ($edit['published'] ?? 'Yes') === 'Yes' ? 'selected' : '' ?>>Yes</option><option value="No" <?= ($edit['published'] ?? '') === 'No' ? 'selected' : '' ?>>No</option></select></div><div class="field full"><button class="btn btn-primary"><?= $edit ? 'Update Batch' : 'Add Batch' ?></button><?php if ($edit): ?><a class="btn btn-soft" href="batches.php">Cancel</a><?php endif; ?></div></div></form><br>
<div class="panel-card"><div class="toolbar"><div><h2 style="margin:0;color:var(--navy)">Batch Timings</h2><p style="margin:4px 0 0;color:var(--muted)">Published batches appear as trust and conversion blocks.</p></div><form method="get"><input name="q" value="<?= e($q) ?>" placeholder="Search batches"><button class="btn btn-sm btn-dark">Search</button></form></div><div class="table-wrap"><table><thead><tr><th>Batch</th><th>Course</th><th>Timing</th><th>Published</th><th>Actions</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td data-label="Batch"><strong><?= e($row['batch_name']) ?></strong><br><span class="help"><?= e($row['days'] ?? '') ?> <?= e($row['seats_note'] ?? '') ?></span></td><td data-label="Course"><?= e($row['course_name'] ?? '-') ?></td><td data-label="Timing"><?= e($row['timing'] ?? '-') ?></td><td data-label="Published"><span class="badge <?= $row['published'] === 'Yes' ? 'badge-converted' : 'badge-notinterested' ?>"><?= e($row['published']) ?></span></td><td data-label="Actions"><div class="table-actions"><a class="btn btn-sm btn-soft" href="batches.php?edit=<?= e((string)$row['id']) ?>">Edit</a><form method="post" onsubmit="return confirm('Delete this batch?')"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= e((string)$row['id']) ?>"><button class="btn btn-sm btn-danger">Delete</button></form></div></td></tr><?php endforeach; ?><?php if (!$rows): ?><tr><td colspan="5" class="empty-state">No batch timings yet.</td></tr><?php endif; ?></tbody></table></div></div>
<?php require_once __DIR__ . '/_footer.php'; ?>
